version: '3.7'
services:
  config-service:
    container_name: config-service
    build:
      context: config-service
      dockerfile: Dockerfile
    image: config-service
    ports:
      - 8888:8888
    expose:
      - 8888
    networks:
      - service-network
    healthcheck:
      test: "curl --fail --silent http://config-service:8888/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  discovery-service:
    container_name: discovery-service
    build:
      context: discovery-service
      dockerfile: Dockerfile
    image: discovery-service
    ports:
      - 8761:8761
    expose:
      - 8761
    networks:
      - service-network
    healthcheck:
      test: "curl --fail --silent http://discovery-service:8761/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      config-service:
        condition: service_healthy
  gateway-service:
    container_name: gateway-service
    build:
      context: gateway-service
      dockerfile: Dockerfile
    image: gateway-service
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - service-network
    depends_on:
      discovery-service:
        condition: service_healthy
  auth-service:
    container_name: auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    image: auth-service
    ports:
      - 8079:8079
    expose:
      - 8079
    networks:
      - service-network
    depends_on:
      discovery-service:
        condition: service_healthy
      auth-mongodb:
        condition: service_started
  first-service:
    container_name: first-service
    build:
      context: first-service
      dockerfile: Dockerfile
    image: first-service
    ports:
      - 8081:8081
    expose:
      - 8081
    networks:
      - service-network
    depends_on:
      discovery-service:
        condition: service_healthy
      first-mongodb:
        condition: service_started
  second-service:
    container_name: second-service
    build:
      context: second-service
      dockerfile: Dockerfile
    image: second-service
    ports:
      - 8082:8082
    expose:
      - 8082
    networks:
      - service-network
    depends_on:
      discovery-service:
        condition: service_healthy
      second-mongodb:
        condition: service_started
  auth-mongodb:
    container_name: auth-mongodb
    image: mongo:latest
    ports:
      - 27000:27017
    expose:
      - 27000
    networks:
      - service-network
    volumes:
      - mongodb-auth:/data/db
  first-mongodb:
    container_name: first-mongodb
    image: mongo:latest
    ports:
      - 27001:27017
    expose:
      - 27001
    networks:
      - service-network
    volumes:
      - mongodb-first:/data/db
  second-mongodb:
    container_name: second-mongodb
    image: mongo:latest
    ports:
      - 27002:27017
    expose:
      - 27002
    networks:
      - service-network
    volumes:
      - mongodb-second:/data/db
volumes:
  mongodb-auth:
  mongodb-first:
  mongodb-second:
networks:
  service-network:
    driver: bridge