version: "3.7"
name: config
services:
  config-service:
    container_name: config-service
    build:
      dockerfile: Dockerfile
    image: reactive/config-service
    ports:
      - "8888:8888"
    expose:
      - 8888
    healthcheck:
      test: "curl --fail --silent http://config-service:8888/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s