apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: reactive/product-service:1.0.0
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: discovery-service
  ports:
    - port: 8091
      targetPort: 8091
