version: "3.7"
name: postgres
services:
  db:
    container_name: "first-postgres"
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=first-postgres
    volumes:
      - postgres-first:/var/lib/postgresql/data
volumes:
  postgres-first: