version: '3.7'
name: mongo
services:
  auth-mongodb:
    container_name: auth-mongodb
    image: mongo:latest
    ports:
      - 27000:27017
    volumes:
      - mongodb-auth:/data/db
  first-mongodb:
    container_name: first-mongodb
    image: mongo:latest
    ports:
      - 27001:27017
    volumes:
      - mongodb-first:/data/db
  second-mongodb:
    container_name: second-mongodb
    image: mongo:latest
    ports:
      - 27002:27017
    volumes:
      - mongodb-second:/data/db
volumes:
  mongodb-auth:
  mongodb-first:
  mongodb-second: